"""Continuous conservative floor sweep from fresh native component bounds."""
import json,hashlib,math
from pathlib import Path
from shapely.geometry import LineString,box,Polygon
ROOT=Path('/workspace/his-office-pinterest');folder=ROOT/'layout';native_path=folder/'chair-transfer-native-check.json';native=json.loads(native_path.read_text());lp=ROOT/'model/layout.json';layout=json.loads(lp.read_text());specs={i['id']:i for i in layout['items']};sha=hashlib.sha256(lp.read_bytes()).hexdigest()
assert sha==native['layout_sha256'],'Native check must match current canonical layout'
path=LineString(native['waypoints_blender_xy_m']);radius=native['chair_caster_diameter_m']/2;sweep=path.buffer(radius,quad_segs=128)
obstacles=[]
for part in native['floor_obstacles']:
 lo,hi=part['world_bounds_m'];shape=box(lo[0],lo[1],hi[0],hi[1]);gap=path.distance(shape)-radius
 obstacles.append({'name':part['name'],'group':part['group'],'conservative_xy_bbox_m':[lo[0],hi[0],lo[1],hi[1]],'minimum_continuous_caster_envelope_clearance_m':gap,'caster_disk_path_clear':gap>=0,'swept_overlap_m2':sweep.intersection(shape).area})
room_path=Path('/workspace/his-office-redesign/geometry/room-measurements.json');room=Polygon(json.loads(room_path.read_text())['outline_blender_xy_m']);rug=specs['rug'];rx,ry=rug['position_blender_m'][:2];rw,rd=rug['external_dimensions_m'][:2];rugshape=box(rx-rw/2,ry-rd/2,rx+rw/2,ry+rd/2);margin_rug=path.distance(rugshape.boundary)-radius
alex=next(p for p in native['floor_obstacles'] if p['group']=='secondary-workspace' and 'alex-drawers' in p['name']);legs=[p for p in native['floor_obstacles'] if p['group']=='secondary-workspace' and 'ADILS' in p['name']];left=alex['world_bounds_m'][1][0];right=min(p['world_bounds_m'][0][0] for p in legs);bay=right-left;target=native['bench_seated_center_m'];caster_side_margins=[target[0]-radius-left,right-(target[0]+radius)]
out={'checkpoint':'Root-approved UPLIFT checkpoint. Refresh if standing desk geometry or any floor footprint changes.','native_source_file':native['source_file'],'native_source_sha256':native['source_sha256'],'canonical_layout_file':str(lp),'canonical_layout_sha256':sha,'native_proof_file':str(native_path),'native_proof_sha256':hashlib.sha256(native_path.read_bytes()).hexdigest(),'method':'Continuous caster-center polyline expanded by official 70.104 cm circle against conservativeXY AABBs of fresh native components entering lowest20cm above floor. Desktop/overhead parts excluded from floor sweep; full chair sampled 3D surface check separately includes them.','waypoints_blender_xy_m':native['waypoints_blender_xy_m'],'steps':['Pull primary chair10cm back','Slide right139.75cm while behind both desktops','Approach35cm toward projectbench knee bay'],'center_path_length_m':path.length,'chair_caster_diameter_m':radius*2,'clear_knee_bay_x_interval_m':[left,right],'clear_knee_bay_width_m':bay,'bench_seated_center_m':target,'caster_side_margins_when_advanced_under_bench_m':caster_side_margins,'continuous_caster_disk_sweep_clear_of_all_tested_floor_components':all(o['caster_disk_path_clear'] for o in obstacles),'minimum_floor_component_clearance_m':min(o['minimum_continuous_caster_envelope_clearance_m'] for o in obstacles),'entire_caster_sweep_within_measured_room_outline':room.covers(sweep),'entire_caster_sweep_on_6x9_rug':rugshape.covers(sweep),'minimum_rug_edge_margin_m':margin_rug,'rug_dimensions_xy_m':[rw,rd],'obstacles':obstacles,'native_3D_sample_count':native['native_sample_count'],'native_3D_no_sampled_unintended_surface_intersections':native['native_no_sampled_unintended_intersections'],'result':'Feasible nominal one-chair transfer between main computer desk and 140×60 cm project bench; no furniture relocation required.','operating_note':'Close ALEX and clothes drawers before chair transfer. Tuck primary chair before open clothes-drawer/rear-passage use; previously documented sequential-use restriction remains.','limits':native['limits']+['Floor projection uses full component AABBs rather than exact curved legs, hence conservative.','Measured model has 5–12 cm outline uncertainty and photo-proxy uncertainty in owned lamp/cat components; this is model planning, not site clearance certification.']}
p=folder/'chair-transfer-check.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:out[k] for k in ['clear_knee_bay_width_m','caster_side_margins_when_advanced_under_bench_m','continuous_caster_disk_sweep_clear_of_all_tested_floor_components','minimum_floor_component_clearance_m','entire_caster_sweep_on_6x9_rug','minimum_rug_edge_margin_m','native_3D_sample_count','native_3D_no_sampled_unintended_surface_intersections']},indent=2))
# Small explanatory engineering plan, generated from measured shapes.
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon as PatchPolygon,Rectangle,Circle
fig,ax=plt.subplots(figsize=(10,6.8));fig.patch.set_facecolor('white');ax.add_patch(PatchPolygon(list(room.exterior.coords),facecolor='#faf8f3',edgecolor='#344253',lw=1.8));ax.add_patch(Rectangle((rx-rw/2,ry-rd/2),rw,rd,facecolor='#ddd9cf',edgecolor='#999387',alpha=.5))
for it in layout['items']:
 if it['id'] not in ['uplift-main-desk','secondary-workspace','visitor-chair','muttros-cat-tree','clothes-dresser']:continue
 x,y=it['position_blender_m'][:2];w,d=it['external_dimensions_m'][:2];ax.add_patch(Rectangle((x-w/2,y-d/2),w,d,fill=False,edgecolor='#8c8276',lw=1));label={'uplift-main-desk':'UPLIFT computer desk','secondary-workspace':'Clear project bench\n140 × 60 cm','visitor-chair':'Visitor','muttros-cat-tree':'Cat tree','clothes-dresser':'Folded clothes'}[it['id']];ax.text(x,y,label,ha='center',va='center',fontsize=8,color='#3e4548',zorder=8,bbox=dict(boxstyle='round,pad=.15',fc='white',ec='none',alpha=.65))
for part in native['floor_obstacles']:
 lo,hi=part['world_bounds_m'];ax.add_patch(Rectangle((lo[0],lo[1]),hi[0]-lo[0],hi[1]-lo[1],facecolor='#283646',edgecolor='none',alpha=.65))
ax.add_patch(PatchPolygon(list(sweep.exterior.coords),facecolor='#90b3a6',edgecolor='#416b5e',alpha=.58,lw=1));xs,ys=path.xy;ax.plot(xs,ys,'o-',color='#235347',lw=1.5,ms=4)
for n,(x,y) in enumerate(native['waypoints_blender_xy_m']):
 ax.text(x-.075 if n<2 else x-.015,y+.045 if n==0 else y-.055,str(n+1),fontsize=10,color='#163f34',ha='right' if n<2 else 'center',va='bottom' if n==0 else 'top',fontweight='bold')
ax.annotate('89.5 cm knee bay',(target[0],-.10),(target[0]+.50,.62),arrowprops=dict(arrowstyle='-',color='#45675b'),fontsize=9,color='#45675b',ha='center');ax.annotate('One chair transfers:\n10 cm back → slide right → approach',(target[0]-.4,-.95),(-4.3,-1.15),arrowprops=dict(arrowstyle='-',color='#45675b'),fontsize=9,color='#45675b',ha='left')
ax.set_title('His office · one-chair transfer at the UPLIFT checkpoint',loc='left',fontsize=15,fontweight='bold',pad=16);ax.set_aspect('equal');ax.set_xlim(-8.18,-2.70);ax.set_ylim(-3.25,.95);ax.axis('off');fig.text(.09,.045,'Continuous 70.1 cm caster sweep clears floor parts; full chair proxy passes 96 sampled 3D checks. Entire caster path remains on rug.',fontsize=8,color='#5b6770');fig.text(.09,.02,'Close drawers for transfer. Scan and owned-product proxy uncertainty apply; verify on site. No accessibility or human-body clearance claim.',fontsize=8,color='#5b6770');fig.savefig(folder/'chair-transfer-plan.png',dpi=190,bbox_inches='tight');fig.savefig(folder/'chair-transfer-plan.pdf',bbox_inches='tight');plt.close(fig)
