from pathlib import Path
import hashlib,json,datetime
from PIL import Image
root=Path('/workspace/his-office-pinterest');out=root/'qa/final-variants'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
manifest_path=root/'images/generation-manifest.json';manifest=json.loads(manifest_path.read_text())
checks={
'a': ['Correct target Camera A with rear door at left, narrow sash window and white pipe, workwall at right; no mirrored or enlarged room topology.', 'One Mineral Aeron faces the small primary desk; project bench remains clear of a second monitor or permanent second chair. Five ALEX drawer fronts are visible; only the existing dresser is partly cropped.', 'Two separate ledges and three books on each, independent Richmond art, desk mat, open-centre Honeywell head and cat-tree levels occupy coherent target positions.', 'B keeps its slat bay and painted upper band; C has its Naval painted wall without panels. The tabletop palm remains a small dresser accessory.'],
'b': ['Correct target Camera B, distinguished by the white closet door, overhead cupboard and living-room entry at right; it is not a repeated Camera A.', 'The foreground owned Aeron is naturally cropped, the visitor chair faces toward the desks, and the fixed project bench has no extra equipment or permanent worker.', 'Richmond art and the low ledge remain above the bench; the high ledge is partly cropped at left. Product omissions outside the view are consistent with target-camera occlusion.', 'B slat bay and C plain Naval wall retain their separate treatments; white doors, trim and cupboard remain white.'],
'c': ['Correct target Camera C with chimney/brick at left, recorded rear door at right, radiator beside the dresser and narrow window at the far right.', 'The fireplace remains a closed white recessed arch with a shallow internal bottom brick course; no open firebox, projecting raised hearth or added mantel.', 'Three dresser drawer fronts are visible; small palm and FADO remain on its top. The single Aeron is cropped at right, the visitor chair at left, and the cat tree appears near the window.', 'No stray cropped Honeywell head is added to this view; its absence agrees with the native camera. The real window frame/sash remains visible.']
}
views=[]
for v in manifest['views']:
 p=root/v['target_output'];orig=Path(v['generator_original_file']);variant=p.parts[-3];camera=v['view'];target=root/'variants'/variant/'model/renders'/f'room-{camera}.jpg';model=root/v['model'];layout=root/v['layout']
 h=sha(p)
 assert h==sha(orig)==v['delivered_sha256']==v['generated_file_sha256'],v['id']
 assert sha(model)==v['model_sha256'];assert sha(layout)==v['layout_sha256']
 for ref,rh in zip(v['referenced_image_paths'],v['reference_sha256']):assert sha(Path(ref))==rh
 with Image.open(p) as im:dimensions=list(im.size)
 with Image.open(target) as im:target_dimensions=list(im.size)
 views.append({'id':v['id'],'status':'PASS FOR CONCEPT VISUALIZATION','variant':variant,'camera':camera,'path':str(p),'sha256':h,'pixels':dimensions,'untouched_generator_original':str(orig),'original_byte_parity':True,'target_native_view':str(target),'target_native_view_sha256':sha(target),'target_pixels':target_dimensions,'native_model_sha256':sha(model),'layout_sha256':sha(layout),'visual_findings':checks[camera],'blocking_geometry_or_facing_failure':False})
assert len(views)==6
report={'schema_version':1,'reviewed_UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'PASS FOR CONCEPT VISUALIZATION','scope':'Independent visual comparison of six final image-generator originals against the six corresponding frozen native target views and original-product reference boards.','metric_validation':False,'authority':'Native models, supplier component parity, source architecture parity and final nominal-route proofs establish modeled geometry and operation. Photographic concepts illustrate appearance and do not certify dimensions, clearances, installation or exact product meshes.','generation_manifest':str(manifest_path),'generation_manifest_sha256':sha(manifest_path),'views':views,'cross_view_consistency':{'distinct_correct_cameras_all_six':True,'one_owned_task_chair_and_one_visitor':True,'clear_fixed_bench':True,'architecture_openings_and_furniture_facing_coherent':True,'B_slat_and_C_plain_paint_coherent':True,'true_occlusion_allowed':True},'residual_variations':['Palm foliage in the generated views is denser/fuller than the thin procedural proxy; A remains somewhat fuller than C, but it stays a tabletop accessory and no floor-route obstruction is introduced. Live-plant appearance and spread require a field check.','Aeron and visitor-chair cushion/mesh/frame silhouettes, drawer seams, shelf lips and cat upholstery/branch detail vary modestly from the proxy and product photographs; these concepts do not replace the product selections or native fit proofs.','Rug, wood grain, art brushwork, brick pattern, daylight, globe glow and exterior scenery are photorealistic generated interpretations.','Camera B can suggest a narrow wall-floor finishing strip; source workwall baseboard geometry is unrecorded, so this is a generated finishing detail, not measured architecture.'],'superseded_attempts':'Initial repeated Camera A outputs and oversized-palm candidates are excluded from acceptance and retained only in generation-manifest history/checkpoints.','model_report':str(out/'QA-REPORT.txt'),'model_report_sha256':sha(out/'QA-REPORT.txt'),'native_render_review':str(out/'final-native-render-visual-QA.json'),'native_render_review_sha256':sha(out/'final-native-render-visual-QA.json')}
(out/'final-image-QA.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['PASS FOR CONCEPT VISUALIZATION — SIX FINAL B/C PHOTOGRAPHIC VIEWS','', 'All three angles for both variants were compared with their corresponding frozen native views and original-product references. The corrected final files use distinct Camera A/B/C projections, preserve the room-opening relationships and furniture facing, and retain one owned task chair, one visitor chair and a clear project bench. B keeps its slat bay; C keeps plain Naval walls. Camera C retains the closed recessed fireplace and shallow internal lower brick course. No blocking architecture, facing, room-topology or furniture-count defect remains.','', 'These are appearance concepts, not metric image validation. The exact modeled positions, dimensions, clearances, desk-height motion and nominal routes remain established by QA-REPORT.txt and the native/export proofs. True crop and occlusion are allowed. Generated palm foliage is fuller than the procedural proxy; chairs, shelf lips, wood/rug/brick/art detail and lighting have modest photorealistic variation. A narrow wall-floor finishing strip suggested in Camera B is unmeasured. Live plant spread and finishing details require site checks.','', 'Each delivered PNG is byte-identical to its recorded image-generator original. Initial repeated Camera A and oversized-palm candidates are superseded and are not accepted. Exact final hashes, native-target hashes, dimensions, manifest and original paths are recorded in final-image-QA.json.','']
for v in views:lines.extend([f"{v['id']}: {v['path']}",f"SHA256 {v['sha256']} ({v['pixels'][0]} x {v['pixels'][1]} pixels)"])
(out/'final-image-QA.txt').write_text('\n'.join(lines)+'\n')
print(json.dumps({'status':report['status'],'json':str(out/'final-image-QA.json'),'json_sha256':sha(out/'final-image-QA.json'),'txt_sha256':sha(out/'final-image-QA.txt'),'views':[{'id':v['id'],'pixels':v['pixels'],'hash':v['sha256']}for v in views]},indent=2))
