import json,pathlib,datetime
P=pathlib.Path('/workspace/his-office-redesign/products/candidates');old=json.loads((P/'official-source-extracts.json').read_text());lookup={d['id']:d for d in old};I=P/'official-images'
rows=[]
def add(id,category,name,color,dims,price,**kw):
 source=lookup.get(id,{})
 r={'id':id,'category':category,'name':name,'selected_color':color,'dimensions_m_W_D_H':dims,'price_USD':price,'price_checked_UTC':'2026-10-08','source_url':kw.pop('source_url',source.get('source_url')),'official_image_file':str(I/(id+('.webp' if id in ['rug-christie','ruggable-inkdrop','art-blue-geometric','art-blue-bold'] else '.jpg'))),'official_image_urls':source.get('official_image_urls',[]),'source_page_file':str(P/'source-pages'/(id+'.html')),'nominal_dimensions_note':'Retailer nominal commercial measurements; not physically measured.'}
 r.update(kw);rows.append(r);return r
add('lagkapten-alex-double','secondary_workspace','IKEA LAGKAPTEN / ALEX desk, two 5-drawer pedestals','Black-brown top / white drawers',[1.4,.6,.73],239.99,sku='094.321.89',rank=1,geometry={'top_W_D_m':[1.4,.6],'pedestal_W_D_H_m':[.36,.58,.70],'pedestal_count':2,'calculated_knee_width_m':.68,'knee_width_is_calculation':True},function='Actual desk-height workspace; 5 drawers on each side. ALEX is office/light-item storage, not the dedicated folded-clothes chest.',material='Foil black-brown grained top; white drawer fronts with cutout pulls; LAGKAPTEN top is a lightweight honeycomb construction, not solid wood.',limits='No verified ALEX internal drawer heights or capacity; do not depict giant clothes drawers. Room planning should include chair base and pullout space.')
add('lagkapten-alex-single','secondary_workspace','IKEA LAGKAPTEN / ALEX desk, one 5-drawer pedestal and two legs','Black-brown top / white drawers and legs',[1.4,.6,.73],159.99,sku='594.321.63',rank=2,geometry={'top_W_D_m':[1.4,.6],'pedestal_W_D_H_m':[.36,.58,.70],'pedestal_count':1,'calculated_knee_width_before_leg_setback_m':1.04},function='Same usable work surface with a wider chair/knee area; best alternative if the separate clothes chest supplies storage.')
add('alex-drawers','component_evidence','IKEA ALEX 5-drawer pedestal','White',[.36,.58,.70],95,sku='004.735.46',verified_inside_drawer_depth_m=.5207,verified_inside_drawer_height_m=None,verified_inside_drawer_width_m=None,verified_storage_volume_m3=None,max_load_per_drawer_lb=9,max_load_small_drawer_lb=4,max_load_total_lb=26,limits='Retailer only supplies interior depth. No verified clothes-storage volume; keep the separate clothes chest.')
add('nordli-clothes','folded_clothes_storage','IKEA NORDLI 4-drawer low dresser','White',[.8,.47,.53],249.99,sku='505.890.78',rank=1,source_url='https://www.ikea.com/us/en/p/nordli-4-drawer-dresser-white-50589078/',storage_capacity_cuft=2.8,storage_capacity_m3=.079287171456,verified_inside_drawer_depth_m=.371475,geometry={'drawer_layout':'2 columns × 2 rows; broad cutout handles; low plinth','height_correction':'Current US 4-drawer model is only 53 cm high, not the older tall modular dresser.'},official_image_urls=['https://www.ikea.com/us/en/images/products/nordli-4-drawer-dresser-white__1293673_pe938442_s5.jpg'],limits='Dedicated folded-clothes storage. Source calls for securing to wall. Current page rating 2.6/5 from 31 reviews, mostly mixed assembly feedback; alternate below has warmer finish and greater published capacity.')
add('storklinta-low-drawers','folded_clothes_storage','IKEA STORKLINTA 3-drawer dresser','Oak effect',[.7,.48,.75],149.99,sku='805.592.92',rank=2,storage_capacity_cuft=4.2,storage_capacity_m3=.118930757184,verified_inside_drawer_W_D_m=[.6096,.40005],verified_drawer_pullout_m=.276225,material='Oak-effect surfaces; modern closed flush drawer fronts.',limits='Dedicated clothes dresser, not a second desk. Anchor/unlock wall attachment is part of the product design.')
add('grejig-shoes','shoes','IKEA GREJIG stackable shoe rack','Gray',[.58,.27,.17],4.99,sku='206.200.61',rank=1,source_url='https://www.ikea.com/us/en/p/grejig-shoe-rack-gray-20620061/',recommended_quantity=2,max_stack_quantity=3,capacity_pairs_per_unit=3,placement_intent='Inside the bottom of existing closet if its internal depth/width allows, preserving hanging access and approach.',official_image_urls=['https://www.ikea.com/us/en/images/products/grejig-shoe-rack-gray__1453545_pe992063_s5.jpg'],material='Powder-coated steel wire/mesh; actual official photo governs appearance.')
add('trones-shoes','shoes','IKEA TRONES shoe/storage cabinet, 2-pack','Black',[.52,.18,.39],39.99,sku='803.973.13',rank=2,source_url='https://www.ikea.com/us/en/p/trones-shoe-storage-cabinet-black-80397313/',price_unit='2-pack',dimension_unit='Each cabinet',capacity_pairs_per_unit=4,placement_intent='Alternative only if closet rack fails fit; keep the door/stair/closet route clear.',material='Matte polypropylene tilting bins, not wood drawers.',official_image_urls=['https://www.ikea.com/us/en/images/products/trones-shoe-storage-cabinet-black__0710712_pe727733_s5.jpg'],limits='Requires wall attachment; two vertically stacked units total about 78 cm high before mounting offset.')
add('ekenaset-turquoise','visitor_lounge','IKEA EKENÄSET armchair','Kelinge gray-turquoise',[.64,.78,.76],329,sku='905.334.85',rank=1,seat_W_D_H_m=[.5588,.498475,.45085],armrest_height_m=.62865,material='Actual photographed cool dark gray-turquoise/slate-teal corduroy upholstery, warm brown wooden arms and legs.',availability_note='Current official page says Last Chance; store/delivery availability needs the destination ZIP.',function='Compact relaxed visitor chair; foam and spring seat. Do not count its reclined lounge posture as a full task-chair workstation.')
add('ekenaset-beige','visitor_lounge','IKEA EKENÄSET armchair','Kilanda light beige',[.64,.78,.76],199,regular_price_USD=299,sku='305.334.93',rank=2,seat_W_D_H_m=[.5588,.498475,.45085],material='Light beige woven upholstery, warm brown wooden frame.',availability_note='Current sale while supply lasts. Neutral fallback; blue remains in art/rug if this replaces turquoise.')
r=add('branch-pro','task_seating','Branch Ergonomic Chair Pro, mesh / standard cylinder','Black',[.635,.6096,1.04648],499,rank=1,sku='40553208840227',selected_variant_url='https://www.branchfurniture.com/products/ergonomic-chair-pro?variant=40553208840227',height_range_m=[.9652,1.04648],base_diameter_m=.70104,collision_footprint_m=[.70104,.70104],material='Black mesh back, upholstered black seat, black 5-star caster base.',function='14 adjustments, 5D armrests, height/depth adjustable lumbar, seat-depth and forward-tilt adjustments; available black variant.',limits='Base is wider than the advertised body width; plan 70.1 cm rolling footprint plus movement.',official_image_file=str(I/'branch-pro-selected.jpg'),official_image_urls=['https://cdn.shopify.com/s/files/1/0124/5662/4187/files/ERGPRO_RENDER1_-1.jpg?v=1774561270'])
add('branch-verve','task_seating','Branch Verve Chair, standard','Galaxy (near charcoal / dark midnight blue)',[.6858,.6858,1.0414],599,rank=2,sku='39633980260387',selected_variant_url='https://www.branchfurniture.com/products/verve-chair?variant=39633980260387',height_range_m=[.9398,1.0414],seat_height_range_m=[.4191,.5207],seat_depth_range_m=[.4191,.4826],material='Deep near-charcoal Galaxy knit back, upholstered seat and 5-star casters; use actual official selected-color photo.',function='Adjustable lumbar, seat depth, tilt/tilt lock and arm height; smaller 68.6 cm overall footprint.',official_image_file=str(I/'branch-verve-selected.jpg'),official_image_urls=['https://cdn.shopify.com/s/files/1/0124/5662/4187/files/20220513_VerveChair_FrontPersp_DarkBlue.jpg?v=1742415579'])
add('rug-christie','rug','Rugs USA Christie Washable Modern rug, 5×8 ft','Charcoal / ivory',[1.524,2.4384,.00254],54.99,regular_price_USD=149.99,rank=1,sku='200BIRV71A-508',variant_id=47065110544440,selected_variant_url='https://www.rugsusa.com/products/christie-washable-modern-rug-charcoal?variant=47065110544440',material='100% polyester, power-loomed, 0.10 inch / 2.54 mm pile.',style='Bold angular architectural maze / stepped charcoal-and-ivory geometry. Low pile supports rolling chairs better than shag.',limits='Rug pad is separate; exact placement depends on circulation and fireplace keep-clear area.')
add('ruggable-inkdrop','rug','Ruggable Jonathan Adler Inkdrop Slate Blue, Flatwoven 5×7 ft + Standard Pad','Slate blue / ivory',[1.524,2.1336,.005175],299,rank=2,sku='RUG-SYS-IND-RCT-CHN-JA016-05x07',variant_id=39402849796151,selected_variant_url='https://ruggable.com/products/jonathan-adler-inkdrop-slate-blue-rug?variant=39402849796151',material='2 mm polyester flatwoven washable cover + 1/8 inch (3.175 mm) Standard Pad; 5.175 mm combined nominal thickness is calculated.',style='Ivory field with dark blue stepped ink-line architectural geometry.',limits='Use selected 5×7 flatwoven Standard Pad bundle at $299. Page default $429 is for 6×9; cushioned bundle $359; cover alone $219.')
for id,name,sku,style in [('art-blue-geometric','Desenio Blue Geometric Print, nominal 20×28 in','17414-8','Bold blue circles and semicircles with cream and warm sand architectural shapes.'),('art-blue-bold','Desenio Bold Blue Print, nominal 20×28 in','20012-8','Expressive cobalt form with warm ocher/brown countershape and off-white field.')]:
 add(id,'graphic_art',name,'Blue / cream / warm neutral',[.508,.0,.7112],44.07,regular_price_USD=73.45,sku=sku,rank=1 if id=='art-blue-geometric' else 2,style=style,price_valid_until='2026-10-08',limits='Print only; frame extra. Nominal US 20×28 label is rounded; companion frame description uses physical 19.7×27.6 in (about 50×70 cm). Avoid claiming sub-centimeter verified size.')
add('art-black-frame','art_frame','Desenio Black wood picture frame, nominal 20×28 in','Black',[.5,.0,.7],59.46,regular_price_USD=69.95,sku='AASP-50104',source_url='https://desenio.com/p/frames/wood-frames/black-wood-frames/black-picture-frame-20-x-28-in/',price_valid_until='2026-10-08',material='Black painted yellow-poplar wood, clear acrylic front.',dimensions_note='Dimensions here are approximate picture opening from description 19.7×27.6 in; outside frame width/height and profile depth not published. Use matching retailer nominal 20×28 artwork/frames, not a guessed exact external frame size.',official_image_urls=['https://media.desenio.com/site_images/67f83a345d339427fa9a8c22_1809291497_AASP-50104_variant_main_image_DS.jpg'])
bundle={'version':'his-office-warm-modern-studio-candidates-2026-10-08','scope':'New proposals from current real retailer products, independent of Amy’s original design. No model or image-generation output modified.','price_note':'US prices inspected 2026-10-08 before tax/shipping, dependent on variant and promotional stock. IKEA local availability is not verified without a ZIP.','palette':{'architecture':'Preserve measured existing light wood floor, brick fireplace, doors/closet and windows. Calm warm-white walls.','new_items':'Black-brown worktop, white closed storage, charcoal/ivory graphic rug, slate-teal accent upholstery, warm brown wood, selective bold cobalt art.','keepers':'User’s Pheasantwood 42×30 in UPLIFT top / industrial gray C-frame, white Honeywell 02E Pro lamp and brown MUTTROS 59-inch wicker basket cat tree.'},'recommended_for_parent_to_choose':{'secondary_workspace':'lagkapten-alex-double','folded_clothes_storage':'nordli-clothes','visitor_lounge':'ekenaset-turquoise','shoes':'grejig-shoes × 2, inside existing closet if physically compatible','rug':'rug-christie','task_seating':'branch-pro (1 or 2 according to final two-workstation plan)','graphic_art':'art-blue-geometric + art-black-frame; optional companion Bold Blue'},'meaningful_alternatives':{'secondary_workspace':'Single ALEX desk is cheaper and gives more knee/chair space; dedicated clothes chest still supplies clothes capacity.','folded_clothes_storage':'STORKLINTA oak effect is 70 cm wide, costs $100 less and has greater published capacity, but is 75 cm tall.','rug':'Ruggable 5×7 flatwoven is smaller/easier to fit and adds blue; costs more.','visitor_lounge':'Beige EKENÄSET fallback if Last Chance turquoise is unavailable.'},'excluded':'No PAX/wardrobe: existing closet already handles hanging storage. No Amy furniture carried forward automatically. No dresser top substituted for usable knee-space work surface.','items':rows}
(P/'product-shortlist.json').write_text(json.dumps(bundle,indent=2))
lines=['Warm modern studio — verified product shortlist','US pages checked 2026-10-08; prices before tax/shipping. No purchasing or model edits performed.','Primary palette: existing brick/light oak + Pheasantwood/gray UPLIFT + black-brown secondary desktop + white closed storage + charcoal/ivory graphic rug + actual slate-teal EKENÄSET + bold cobalt architectural art.','']
for r in rows:
 if r['category']=='component_evidence':continue
 dims=r['dimensions_m_W_D_H'];lines += [f"{r['category']}: {r['name']} — {r['selected_color']}",f"  W/D/H nominal m: {dims}; USD ${r['price_USD']:,.2f}"+(f" (regular ${r['regular_price_USD']:,.2f})" if 'regular_price_USD' in r else ''),f"  {r['source_url']}",f"  Official photo: {r['official_image_file']}"]
 if r.get('limits'):lines.append('  '+r['limits'])
 lines.append('')
lines += ['Storage honesty: ALEX retailer confirms 52.1 cm internal drawer depth but no interior width/height/volume. Treat as office bits/light folded items, with NORDLI/STORKLINTA as actual clothes storage.','NORDLI is current LOW 4-drawer 80×47×53 cm ($249.99, 2.8 cu.ft), not a guessed older tall modular unit. STORKLINTA oak effect 70×48×75 cm ($149.99, 4.2 cu.ft) is a useful stronger-capacity alternative.','Desk clear knee bay (calculated): double ALEX 140−2×36=68 cm; single pedestal opens more width. Plan rolling chair footprints and full closet approach in measured geometry.','Source-authored downloadable IKEA 3D assets for ALEX, NORDLI and STORKLINTA also saved in official-3d-assets/ with source URLs; geometry still requires final import/bbox verification by model agent.']
(P/'product-shortlist.txt').write_text('\n'.join(lines)+'\n')
print(json.dumps({'items':len(rows),'json':str(P/'product-shortlist.json'),'txt':str(P/'product-shortlist.txt')}))
