import hashlib, json, pathlib, shutil
from PIL import Image

base = pathlib.Path('/workspace/his-office-pinterest/products')
folder = base / 'composition-pieces'
date = '2026-10-08'

def asset(filename, url, description, inspected=True):
    path = folder / filename
    record = {'path': str(path), 'url': url, 'sha256': hashlib.sha256(path.read_bytes()).hexdigest(), 'bytes': path.stat().st_size, 'original_bytes': True, 'description': description, 'visually_inspected': inspected}
    if path.suffix.lower() in ['.jpg', '.png']:
        im = Image.open(path)
        record.update(pixels=list(im.size), format=im.format)
    return record

def source_record(id, category, name, sku, price, qty, url, dimensions, notes, photo, geometry=None):
    return {'id': id, 'category': category, 'name': name, 'sku': sku, 'price_USD': price, 'quantity': qty, 'line_total_USD': round(price * qty, 2), 'source_url': url, 'price_checked_date': date, 'selection_status': 'Selected by root for both B/C composition; not purchased.', 'dimensions_m_W_D_H': dimensions, 'dimensions_note': notes, 'official_photos': [photo], 'geometry': geometry or {'type': 'Dimensioned/photo-guided proxy, not supplier CAD'}, 'source_details_file': str(folder / 'finishing-selected-products.json')}

cad = json.loads((folder / 'official-assets-bounds.json').read_text())
source_components = json.loads((folder / 'fado-source-components.json').read_text())
lamp_parts = [source_components['components'][i] for i in [0, 1, 3, 4]]
lamp_min = [min(c['world_min_m'][i] for c in lamp_parts) for i in range(3)]
lamp_max = [max(c['world_max_m'][i] for c in lamp_parts) for i in range(3)]
lamp_body = {'measurement_method': 'Connected components of original manufacturer mesh, temporary in-memory weld for measurement only; original GLB unchanged.', 'included_components_by_vertices': [7426, 2097, 896, 896], 'excluded': 'Cord, inline switch and cable-entry pieces', 'native_body_min_m': lamp_min, 'native_body_max_m': lamp_max, 'native_body_dimensions_m': [lamp_max[i] - lamp_min[i] for i in range(3)], 'native_body_center_XY_m': [(lamp_max[0] + lamp_min[0])/2, (lamp_max[1] + lamp_min[1])/2], 'catalog_body_diameter_height_m': [.254, .2286], 'model_recommendation': 'Use catalog-dimensioned body proxy with the actual globe/base silhouette, disclosing source CAD versus catalog envelope adjustment. Route cord independently. Do not rescale the whole cord-inclusive source GLB to the globe diameter.'}
(folder / 'fado-body-measurements.json').write_text(json.dumps(lamp_body, indent=2) + '\n')

shelf = source_record('mosslanda-black-display-ledge', 'display_shelving', 'IKEA MOSSLANDA black picture/display ledge, 115cm', '702.921.04', 19.99, 2, 'https://www.ikea.com/us/en/p/mosslanda-picture-ledge-black-70292104/', cad['mosslanda']['dimensions_m'], 'Official 1:1 supplier GLB: 1.149935W×.120000D×.070000H meters. US rounded label45¼×4¾in differs slightly; 12cm includes front/back lips and is not usable tray depth.', asset('mosslanda-black-original.jpg', 'https://www.ikea.com/us/en/images/products/mosslanda-picture-ledge-black__0634120_pe696314_s5.jpg', 'Original IKEA black MOSSLANDA product photo, no image editing.'), {'type': 'Official IKEA GLB', 'asset': asset('mosslanda-official.glb', 'https://web-api.ikea.com/dimma/assets/1.2/70292104/PS01_S01_NV01/isp3/glb/70292104_PS01_S01_NV01_ISP3_2.0_1ef2619cca174365bf915b96c1518f6a.glb?cn=pip', 'Official black ledge geometry, native glTF Y-up; Blender importer converts to Z-up.', False), 'bounds_file': str(folder / 'official-assets-bounds.json'), 'scale': 'Preserve supplier meters 1:1.'})
shelf.update(max_load_kg=7.4989, max_load_source_lb=16.53, max_picture_height_m=.45085, materials='Fiberboard with paper foil.', mounting_note='Screws/wall hardware not included. Select fasteners for substrate; through any acoustic panel/felt into suitable structural wall support, not supported by felt or adhesive alone.', art_relationship='Richmond70cm-high print is independently wall-mounted; do not lean it on ledge whose published picture-height limit is45cm.', placement_intent=[{'where':'Above fixed project bench','center_height_m':1.25,'contents':'A few illustrative small books/low objects only.'},{'where':'Above primary standing desk','center_height_m':2.10,'bottom_approx_m':2.03,'contents':'A few illustrative small books; verify monitor at full desk lift before installation.'}], availability_note='IKEA metadata InStock on research date; local store/ZIP availability not checked.', source_page_file=str(folder / 'mosslanda.html'))

lamp = source_record('fado-kajplats-opal-table-lamp', 'decorative_table_lighting', 'IKEA FADO / KAJPLATS white opal-glass table lamp, smart white/color bulb + remote kit', '296.549.71', 44.98, 1, 'https://www.ikea.com/us/en/p/fado-kajplats-table-lamp-with-led-bulb-smart-color-and-white-spectrum-s29654971/', [.254, .254, .2286], 'US published lamp bodyØ10in×H9in. Official source bodyØ.239882×H.236489m differs from rounded catalog; entire cord-inclusive CAD X.472768m is not body diameter. Both original CAD and explicit separated-body measurements retained.', asset('fado-white-original.jpg', 'https://www.ikea.com/us/en/images/products/fado-table-lamp-white__0606976_pe682645_s5.jpg', 'Original pure FADO globe component photo; selected complete kit includes bulb and remote.'), {'type':'Original supplier CAD reference; catalog-dimensioned body proxy permitted with disclosed source-envelope difference.', 'asset':asset('fado-official.glb','https://web-api.ikea.com/dimma/assets/1.2/70096377/PS01_S01_NV01/iqp3/glb/93bd49030f65437d811a53b42db2f382-70096377_PS01_S01_NV01_IQP3_2.0.glb?cn=pip','Official FADO body/cord/switch mesh; no scaling to entire source bounding box.',False), 'body_measurements':lamp_body, 'body_measurements_file':str(folder / 'fado-body-measurements.json'), 'original_overall_bounds':cad['fado']})
lamp['official_photos'].append(asset('fado-kajplats-kit-original.jpg','https://www.ikea.com/us/en/images/products/fado-kajplats-table-lamp-with-led-bulb-smart-color-and-white-spectrum__1560525_pe1025400_s5.jpg','Original actual kit photograph showing white globe, bulb and remote.'))
lamp.update(components=[{'id':'700.963.77','name':'FADO white glass table lamp','quantity':1},{'id':'906.114.78','name':'KAJPLATS E26 smart white/color bulb and remote starter kit','quantity':1}], luminous_flux_lm=1055, bulb_power_W=8, rated_lifetime_h=25000, default_CCT_K=2700, selectable_white_CCT_K=[2200,2700,4000,6500], remote_control_note='Kit pre-paired, remote included. Basic included-remote use does not require app/hub; optional Matter-enabled hub/app adds functions. Remote power/batteries to check at installation; batteries not priced as a selected product.', materials='White opal glass shade, polypropylene base.', cord_length_published_m=1.8034, cord_note='Bundle page5ft11in; standalone lamp page6ft1in. Route actual cord to outlet and verify reach, not through circulation.', family_price_note='IKEA Family$34.98 Oct7–Nov11 2026 or while supplies last, membership conditional; budget uses regular$44.98.', availability_note='Local store/ZIP availability not checked.', placement_intent='On folded-clothes dresser opposite compact palm; central tray/top remains useful.', source_page_file=str(folder / 'fado-kajplats.html'), source_reliability_note='Use written product details/technical specifications. Auto-caption describing touch-sensitive lamp is not taken as control evidence; actual selected control is included remote.')

mat = source_record('grovemade-dark-grey-medium-plus', 'desk_organization', 'Grovemade Wool Felt Desk Pad, Dark Grey / Medium Plus', 'FG-DESKPAD-WOOL-MDP-DKGREY', 100.0, 1, 'https://grovemade.com/product/wool-felt-desk-pad/?initial=683', [.9652,.40005,.0035], 'Exact38W×15.75D inches converted to meters; technical specifications say3.5mm thick while intro says3mm. Render uses3.5mm technical value. No supplier CAD found.', asset('grovemade-darkgrey-mediumplus-original.jpg','https://grovemade.com/shop-static/shop/variant/grovemade-woolfelt-desk-pad-dark-deepmedium-galA-A1.jpg?_v=1631199017.5250502','Original selected MediumPlus DarkGrey product photo; pictured keyboard/mouse/mug are supplier styling and not included purchases.'))
mat.update(variant_id=683, materials='Premium German virgin Merino wool felt, vegetable-tanned leather label.', fit_note='On120×68.5cm primary desk leaves about11.74cm each side when centered and28.495cm total remaining depth. Does not cover or join the independent project bench.', use_note='Manufacturer says not designed as a writing surface; works with optical mice. Fixed project bench remains available for handwriting/project work.', availability_note='Manufacturer lists InStock, ships in2weeks on research date; destination delivery not checked.', source_page_file=str(folder / 'grovemade-felt-mediumplus.html'))

plant = source_record('sill-small-parlor-westcott-black', 'live_tabletop_greenery', 'The Sill Small Parlor Palm + Westcott Black ceramic planter/saucer', 'BN-PAL-PAR-4-WC5BK', 79.0, 1, 'https://www.thesill.com/products/parlor-palm?variant=41732265410665', [.127,.127,.2794], 'Product variant labels small plant6–11in tall from nursery-pot bottom to foliage top (.1524–.2794m), planter4.75in wide; separate official Westcott page rounds small planter5in=.127m outerdiameter. .2794m is upper source plant height used as design envelope, not guaranteed full outer-pot assembly height or measured delivered specimen. Pot height and crown diameter unpublished; any proxy must disclose those shape/size assumptions. No supplier CAD.', asset('sill-small-parlor-westcott-black-original.jpg','https://cdn.shopify.com/s/files/1/0150/6262/files/the-sill_Small-Parlor-Palm_Small_Westcott_Black_Variant.jpg?v=1770151098','Original exact available small ParlorPalm/WestcottBlack variant photograph; preserve complete image and never enlarge into a floor tree.'))
plant.update(variant_id=41732265410665, exact_species='Chamaedorea elegans', common_name='Parlor Palm / Neanthe Bella Palm', species_source_url='https://www.thesill.com/blogs/plants-101/how-to-care-for-bamboo-palm-chamaedorea-seifrizii', species_source_note='The retailer care article has a legacy bamboo-palm slug but current title/text explicitly identify ParlorPalm as Chamaedorea elegans.', pet_evidence={'authority':'ASPCA','url':'https://www.aspca.org/pet-care/aspca-poison-control/toxic-and-non-toxic-plants/parlor-palm','species':'Chamaedorea elegans','statement':'Non-toxic to cats and dogs','source_page_file':str(folder / 'aspca-parlor.html')}, published_plant_height_range_m=[.1524,.2794], planter_diameter_label_m=.12065, conservative_planter_diameter_m=.127, nursery_diameter_m=.1016, pot_height_status='Unpublished; photo-guided geometry assumption only.', plant_crown_width_status='Unpublished and naturally variable; tabletop decorative proxy, not a verified floor circulation envelope.', planter_details='Westcott ceramic bowl planter with drainage hole and matching saucer; live plant arrives in nursery grow pot nestled in selected outer planter.', placement_intent='On dresser opposite FADO; no floor palm and not on MOSSLANDA usable tray.', growth_note='Each live plant varies by season/specimen. Keep source small size; do not use mature plant height as current delivery dimensions.', availability_note='Exact Shopify variant available=true on research date; price$79 USD. Shipping/tax not checked.', source_page_file=str(folder / 'sill-parlor.html'), variant_source_file=str(folder / 'sill-parlor-js.json'), planter_source_url='https://www.thesill.com/products/westcott-planter', planter_source_file=str(folder / 'sill-westcott-js.json'))

items = [shelf,lamp,mat,plant]
details = {'version':'selected-composition-pieces-2026-10-08','research_date':date,'status':'Root-selected shared finishing pieces for B/C; no purchases/model edits by product researcher.','items':items,'additions_subtotal_USD':round(sum(i['line_total_USD'] for i in items),2),'styling_assumptions':'A few small books and one central dresser tray are illustrative unpriced props, not selected/owned product claims.','floor_plant':'No floor plant selected. Actual Kentia source research retained as rejected/unfit-verified reference under plant/plant-proposal.json.'}
(folder / 'finishing-selected-products.json').write_text(json.dumps(details,indent=2)+'\n')

catalog_path = base / 'selected-products.json'
catalog = json.loads(catalog_path.read_text())
checkpoint = base / 'checkpoints' / 'selected-products-owned-aeron-before-composition-checkpoint-2026-10-08.json'
if not checkpoint.exists():
    shutil.copyfile(catalog_path,checkpoint)
    if (base/'selected-products.txt').exists():shutil.copyfile(base/'selected-products.txt',checkpoint.with_suffix('.txt'))
ids = {v['id'] for v in items}
catalog['items'] = [v for v in catalog['items'] if v['id'] not in ids] + items
shared = round(sum(i['line_total_USD'] for i in catalog['items']),2)
catalog['version']='selected-cohesive-B-C-owned-aeron-mineral-composition-2026-10-08'
catalog['scope']='Two separate cohesive B/C office compositions with owned Mineral Aeron C, shared actual functional furniture, two black display ledges, a charcoal felt desk mat, opal FADO lamp and compact tabletop palm. No purchases.'
catalog['total_new_items_before_tax_shipping_USD']=shared
catalog['price_note']='Oct8 current source research. Owned Aeron costs$0. Twelve selected new product/assembly lines include two MOSSLANDA ledges and three GREJIG racks. RegularFADO kit price used; member discount conditional. Paint/install/tax/shipping and illustrative book/tray styling costs excluded.'
catalog['source_checkpoints'] = list(dict.fromkeys(catalog.get('source_checkpoints',[])+[str(checkpoint)]))
catalog['composition_source_records_file']=str(folder/'finishing-selected-products.json')
catalog['lighting_note']='Use existing overhead light with neutral/cool visual presentation; overhead dimmability/CCT/illuminance unverified. New FADO/KAJPLATS kit has included remote with verified2200/2700/4000/6500K white presets and1055lm rated bulb. Optional evening wall wash is illustrative, not a selected electrical fixture.'
catalog['design_palette'] += ' Two shallow black ledges repeat across both work sections, with graphite felt on primary desk and opal lamp/compact palm on the dresser; dark finish wraps workwall and adjacent windowwall, white trim/ceiling retained.'
catalog['styling_assumptions']=details['styling_assumptions']
catalog['designs']['B']['chosen_design_quantity']=5
catalog['designs']['B']['chosen_design_material_subtotal_usd']=974.75
catalog['designs']['B']['proposed_bay']='Root-selected cohesive revision: five full60cm-width BlackAsh panels form3.0mW×2.4mH bay across both independent work sections. Surrounding Peppercorn charcoal wraps workwall and adjacent windowwall; white trim/ceiling and existing brick retained. Material subtotal$974.75 excludes trims/fasteners/install/tax/shipping. Shelf mounts through panel/felt to suitable wall support.'
catalog['designs']['B']['chosen_scope']='Peppercorn workwall AND adjacent windowwall with3m BlackAsh/blackfelt bay; white trim/ceiling retained.'
catalog['designs']['C']['chosen_scope']='Separate C design: plain deepNaval workwall AND adjacent windowwall, no slats. White trim/ceiling, brick and measured geometry retained.'
catalog['budgets'].update(shared_new_furniture_before_tax_shipping_USD=shared, shared_composition_additions_USD=details['additions_subtotal_USD'], B_panel_quantity=5, B_panel_subtotal_USD=974.75, B_shared_furniture_plus_panels_USD=round(shared+974.75,2), C_shared_furniture_USD=shared)
catalog_path.write_text(json.dumps(catalog,indent=2)+'\n')
lines=['Selected cohesive B/C office products — composition update2026-10-08','No purchases. Earlier owned-chair/furniture checkpoint preserved.','']
for i in catalog['items']:lines.append(f"{i['quantity']} × {i['name']} — ${i['line_total_USD']:.2f} — {i['source_url']}")
lines += ['', 'Owned: Herman Miller Aeron Large/SizeC, Mineral lightgray; Honeywell02E and MUTTROS cat tree retained — $0',f'Shared new furniture + finishing pieces: ${shared:,.2f}',f"Finishing additions: ${details['additions_subtotal_USD']:.2f} (two ledges, lamp kit, mat, compact potted palm)",f"B: FIVE BlackAsh panels$974.75; shared+panels ${shared+974.75:,.2f}; Peppercorn paint/trims/install/tax/shipping pending.",f"C: same shared furniture ${shared:,.2f}; Naval paint/prep/tax/shipping pending.",'Dark finish wraps workwall and adjacent windowwall; white trim/ceiling retained.','No floor palm. Compact real small palm on dresser opposite lamp. Small books and tray are illustrative/unpriced.','FADO body source/catalog discrepancy and plant proxy assumptions explicitly recorded.']
(base/'selected-products.txt').write_text('\n'.join(lines)+'\n')
assert details['additions_subtotal_USD']==263.96
assert shared==2334.06
assert round(shared+974.75,2)==3308.81
print(json.dumps({'catalog':str(catalog_path),'details':str(folder/'finishing-selected-products.json'),'shared_USD':shared,'B_USD':round(shared+974.75,2),'additions_USD':details['additions_subtotal_USD'],'item_ids':list(ids),'fado_body':lamp_body},indent=2))
